# Generated by Django 5.2.3 on 2025-10-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rule_type', models.CharField(choices=[('amount', 'Amount Threshold'), ('keyword', 'Keyword Match'), ('timing', 'Timing/Pattern')], max_length=20)),
                ('threshold', models.FloatField(blank=True, help_text='For amount/timing rules', null=True)),
                ('keywords', models.JSONField(blank=True, default=list, help_text='For keyword-based rules')),
                ('risk_points_min', models.FloatField(default=1.0, help_text='Minimum risk score contribution')),
                ('risk_points_max', models.FloatField(default=1.0, help_text='Maximum risk score contribution')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
