# Generated by Django 5.2.3 on 2025-10-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_api', '0002_ruleconfiguration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruleconfiguration',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='ruleconfiguration',
            name='risk_points_max',
        ),
        migrations.RemoveField(
            model_name='ruleconfiguration',
            name='risk_points_min',
        ),
        migrations.AddField(
            model_name='ruleconfiguration',
            name='risk_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ruleconfiguration',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='ruleconfiguration',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ruleconfiguration',
            name='rule_type',
            field=models.CharField(choices=[('amount_threshold', 'Amount Threshold'), ('keyword', 'Keyword'), ('odd_day', 'Odd Day Pattern')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ruleconfiguration',
            name='threshold',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
