# Generated by Django 5.2.3 on 2025-10-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_api', '0004_alter_transaction_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruleconfiguration',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='ruleconfiguration',
            name='rule_type',
        ),
        migrations.RemoveField(
            model_name='ruleconfiguration',
            name='threshold',
        ),
        migrations.AddField(
            model_name='ruleconfiguration',
            name='category',
            field=models.CharField(choices=[('behavioral', 'Behavioral / Peer'), ('network', 'Network / Relationship'), ('temporal', 'Temporal / Time-based'), ('ml', 'Machine Learning / Anomaly')], default='behavioral', max_length=50),
        ),
        migrations.AddField(
            model_name='ruleconfiguration',
            name='conditions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='transaction',
            name='alert_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
