# Generated by Django 5.2.3 on 2025-10-05 09:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_api', '0005_remove_ruleconfiguration_keywords_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruleconfiguration',
            name='conditions',
        ),
        migrations.AddField(
            model_name='ruleconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ruleconfiguration',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ruleconfiguration',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ruleconfiguration',
            name='field',
            field=models.CharField(default=django.utils.timezone.now, help_text='Field name in Transaction model (e.g., amount, description)', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ruleconfiguration',
            name='operator',
            field=models.CharField(choices=[('>', 'Greater Than'), ('>=', 'Greater Than or Equal'), ('<', 'Less Than'), ('<=', 'Less Than or Equal'), ('==', 'Equals'), ('!=', 'Not Equals'), ('contains', 'Contains Text')], default='>=', max_length=10),
        ),
        migrations.AddField(
            model_name='ruleconfiguration',
            name='value',
            field=models.CharField(default=django.utils.timezone.now, help_text='Value to compare against', max_length=100),
            preserve_default=False,
        ),
    ]
