# Generated by Django 5.2.3 on 2025-10-05 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml_api', '0006_remove_ruleconfiguration_conditions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleconfiguration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ruleconfiguration',
            name='field',
            field=models.CharField(help_text='Field in Transaction model (e.g., amount, description)', max_length=100),
        ),
    ]
